insert into categories (id,name,birth_years,min_birth_year,max_birth_year,players_on_field,min_players_on_field,game_time,break_time) values ('sub6','Sub 6','2020 – 2021',2020,2021,7,5,'15 - 15 minutos','5 minutos') on conflict (id) do nothing;
insert into categories (id,name,birth_years,min_birth_year,max_birth_year,players_on_field,min_players_on_field,game_time,break_time) values ('sub8','Sub 8','2018 – 2019',2018,2019,7,5,'15 - 15 minutos','5 minutos') on conflict (id) do nothing;
insert into categories (id,name,birth_years,min_birth_year,max_birth_year,players_on_field,min_players_on_field,game_time,break_time) values ('sub10','Sub 10','2016 – 2017',2016,2017,9,7,'15 - 15 minutos','5 minutos') on conflict (id) do nothing;
insert into categories (id,name,birth_years,min_birth_year,max_birth_year,players_on_field,min_players_on_field,game_time,break_time) values ('sub12','Sub 12','2014 – 2015',2014,2015,9,7,'20 - 20 minutos','5 minutos') on conflict (id) do nothing;
insert into teams (category_id,group_name,name) values ('sub6','Único','JM SPORT');
insert into teams (category_id,group_name,name) values ('sub6','Único','TOLENTINO FC');
insert into teams (category_id,group_name,name) values ('sub6','Único','GUERREROS DE MANCHAY');
insert into teams (category_id,group_name,name) values ('sub6','Único','CLUB DEPORTIVO LARA');
insert into teams (category_id,group_name,name) values ('sub6','Único','RENACE JUVENTUD');
insert into teams (category_id,group_name,name) values ('sub6','Único','BENJAMIN FC');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO A','TOLENTINO FC');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO A','FOVA');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO A','JYB');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO A','DREAM TEAM');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO A','RENACE JUVENTUD');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO A','JM SPORT');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO B','BENJAMIN FC');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO B','VASQUEZ FC');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO B','REMANENTE FC');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO B','GUERREROS DE MANCHAY');
insert into teams (category_id,group_name,name) values ('sub8','GRUPO B','MATHE SPORT');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO A','MATHE SPORT');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO A','FOVA');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO A','TALENTOS DEL SUR');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO A','REMANENTE FC');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO A','SPORTING JF ONCE');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO A','RENACE JUVENTUD');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO A','BENJAMIN FC');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO B','GUERREROS DE MANCHAY');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO B','VASQUEZ FC');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO B','JM SPORT');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO B','TOLENTINO FC');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO B','TALENTOS UNIDOS');
insert into teams (category_id,group_name,name) values ('sub10','GRUPO B','DREAM TEAM');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO A','GUERREROS DE MANCHAY');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO A','TOLENTINO FC');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO A','MATHE SPORT');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO A','SPORTING JF ONCE');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO A','FOVA');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO A','JYB');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO A','BENJAMIN FC');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO B','RENACE JUVENTUD');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO B','JM SPORT');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO B','TALENTOS UNIDOS');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO B','DREAM TEAM');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO B','CLUB DEPORTIVO LARA');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO B','CACHORROS FC');
insert into teams (category_id,group_name,name) values ('sub12','GRUPO B','FOVITA');
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-1-1','sub6','Único',1,'JM SPORT','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-2-2','sub6','Único',2,'JM SPORT','CLUB DEPORTIVO LARA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-1-3','sub6','Único',1,'BENJAMIN FC','CLUB DEPORTIVO LARA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-2-4','sub6','Único',2,'RENACE JUVENTUD','GUERREROS DE MANCHAY','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-1-5','sub6','Único',1,'TOLENTINO FC','GUERREROS DE MANCHAY','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-2-6','sub6','Único',2,'TOLENTINO FC','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-3-7','sub6','Único',3,'GUERREROS DE MANCHAY','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-4-8','sub6','Único',4,'JM SPORT','TOLENTINO FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-3-9','sub6','Único',3,'TOLENTINO FC','CLUB DEPORTIVO LARA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-4-10','sub6','Único',4,'BENJAMIN FC','GUERREROS DE MANCHAY','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-3-11','sub6','Único',3,'RENACE JUVENTUD','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-4-12','sub6','Único',4,'CLUB DEPORTIVO LARA','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-5-13','sub6','Único',5,'BENJAMIN FC','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-5-14','sub6','Único',5,'TOLENTINO FC','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub6-único-5-15','sub6','Único',5,'CLUB DEPORTIVO LARA','GUERREROS DE MANCHAY','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-1-1','sub8','GRUPO A',1,'TOLENTINO FC','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-2-2','sub8','GRUPO A',2,'TOLENTINO FC','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-1-3','sub8','GRUPO A',1,'FOVA','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-2-4','sub8','GRUPO A',2,'JM SPORT','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-1-5','sub8','GRUPO A',1,'JYB','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-2-6','sub8','GRUPO A',2,'FOVA','JYB','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-3-7','sub8','GRUPO A',3,'TOLENTINO FC','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-4-8','sub8','GRUPO A',4,'TOLENTINO FC','JYB','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-3-9','sub8','GRUPO A',3,'RENACE JUVENTUD','JYB','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-4-10','sub8','GRUPO A',4,'DREAM TEAM','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-3-11','sub8','GRUPO A',3,'JM SPORT','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-4-12','sub8','GRUPO A',4,'RENACE JUVENTUD','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-5-13','sub8','GRUPO A',5,'TOLENTINO FC','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-5-14','sub8','GRUPO A',5,'JYB','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-a-5-15','sub8','GRUPO A',5,'DREAM TEAM','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-1-16','sub8','GRUPO B',1,'BENJAMIN FC','MATHE SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-2-17','sub8','GRUPO B',2,'BENJAMIN FC','GUERREROS DE MANCHAY','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-1-18','sub8','GRUPO B',1,'VASQUEZ FC','GUERREROS DE MANCHAY','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-2-19','sub8','GRUPO B',2,'MATHE SPORT','REMANENTE FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-1-bye-20','sub8','GRUPO B',1,'REMANENTE FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-2-bye-21','sub8','GRUPO B',2,'VASQUEZ FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-3-22','sub8','GRUPO B',3,'BENJAMIN FC','REMANENTE FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-4-23','sub8','GRUPO B',4,'BENJAMIN FC','VASQUEZ FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-3-24','sub8','GRUPO B',3,'MATHE SPORT','VASQUEZ FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-4-25','sub8','GRUPO B',4,'REMANENTE FC','GUERREROS DE MANCHAY','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-3-bye-26','sub8','GRUPO B',3,'GUERREROS DE MANCHAY',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-4-bye-27','sub8','GRUPO B',4,'MATHE SPORT',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-5-28','sub8','GRUPO B',5,'REMANENTE FC','VASQUEZ FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-5-29','sub8','GRUPO B',5,'GUERREROS DE MANCHAY','MATHE SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub8-grupo-b-5-bye-30','sub8','GRUPO B',5,'BENJAMIN FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-1-1','sub10','GRUPO A',1,'MATHE SPORT','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-2-2','sub10','GRUPO A',2,'MATHE SPORT','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-1-3','sub10','GRUPO A',1,'FOVA','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-2-4','sub10','GRUPO A',2,'BENJAMIN FC','REMANENTE FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-1-5','sub10','GRUPO A',1,'TALENTOS DEL SUR','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-2-6','sub10','GRUPO A',2,'FOVA','TALENTOS DEL SUR','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-1-bye-7','sub10','GRUPO A',1,'REMANENTE FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-2-bye-8','sub10','GRUPO A',2,'SPORTING JF ONCE',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-3-9','sub10','GRUPO A',3,'MATHE SPORT','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-4-10','sub10','GRUPO A',4,'MATHE SPORT','REMANENTE FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-3-11','sub10','GRUPO A',3,'RENACE JUVENTUD','TALENTOS DEL SUR','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-4-12','sub10','GRUPO A',4,'SPORTING JF ONCE','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-3-13','sub10','GRUPO A',3,'REMANENTE FC','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-4-14','sub10','GRUPO A',4,'FOVA','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-3-bye-15','sub10','GRUPO A',3,'BENJAMIN FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-4-bye-16','sub10','GRUPO A',4,'TALENTOS DEL SUR',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-5-17','sub10','GRUPO A',5,'MATHE SPORT','TALENTOS DEL SUR','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-6-18','sub10','GRUPO A',6,'MATHE SPORT','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-5-19','sub10','GRUPO A',5,'REMANENTE FC','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-6-20','sub10','GRUPO A',6,'TALENTOS DEL SUR','REMANENTE FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-5-21','sub10','GRUPO A',5,'BENJAMIN FC','RENACE JUVENTUD','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-6-22','sub10','GRUPO A',6,'BENJAMIN FC','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-5-bye-23','sub10','GRUPO A',5,'FOVA',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-6-bye-24','sub10','GRUPO A',6,'RENACE JUVENTUD',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-7-25','sub10','GRUPO A',7,'FOVA','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-7-26','sub10','GRUPO A',7,'RENACE JUVENTUD','REMANENTE FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-7-27','sub10','GRUPO A',7,'BENJAMIN FC','TALENTOS DEL SUR','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-a-7-bye-28','sub10','GRUPO A',7,'MATHE SPORT',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-1-29','sub10','GRUPO B',1,'GUERREROS DE MANCHAY','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-2-30','sub10','GRUPO B',2,'GUERREROS DE MANCHAY','TALENTOS UNIDOS','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-1-31','sub10','GRUPO B',1,'VASQUEZ FC','TALENTOS UNIDOS','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-2-32','sub10','GRUPO B',2,'DREAM TEAM','TOLENTINO FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-1-33','sub10','GRUPO B',1,'JM SPORT','TOLENTINO FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-2-34','sub10','GRUPO B',2,'VASQUEZ FC','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-3-35','sub10','GRUPO B',3,'GUERREROS DE MANCHAY','TOLENTINO FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-4-36','sub10','GRUPO B',4,'GUERREROS DE MANCHAY','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-3-37','sub10','GRUPO B',3,'TALENTOS UNIDOS','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-4-38','sub10','GRUPO B',4,'TOLENTINO FC','VASQUEZ FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-3-39','sub10','GRUPO B',3,'DREAM TEAM','VASQUEZ FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-4-40','sub10','GRUPO B',4,'TALENTOS UNIDOS','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-5-41','sub10','GRUPO B',5,'GUERREROS DE MANCHAY','VASQUEZ FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-5-42','sub10','GRUPO B',5,'JM SPORT','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub10-grupo-b-5-43','sub10','GRUPO B',5,'TOLENTINO FC','TALENTOS UNIDOS','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-1-1','sub12','GRUPO A',1,'TOLENTINO FC','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-2-2','sub12','GRUPO A',2,'GUERREROS DE MANCHAY','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-1-3','sub12','GRUPO A',1,'MATHE SPORT','JYB','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-2-4','sub12','GRUPO A',2,'TOLENTINO FC','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-1-5','sub12','GRUPO A',1,'SPORTING JF ONCE','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-2-6','sub12','GRUPO A',2,'MATHE SPORT','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-1-bye-7','sub12','GRUPO A',1,'GUERREROS DE MANCHAY',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-2-bye-8','sub12','GRUPO A',2,'JYB',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-3-9','sub12','GRUPO A',3,'GUERREROS DE MANCHAY','JYB','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-4-10','sub12','GRUPO A',4,'GUERREROS DE MANCHAY','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-3-11','sub12','GRUPO A',3,'BENJAMIN FC','FOVA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-4-12','sub12','GRUPO A',4,'JYB','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-3-13','sub12','GRUPO A',3,'TOLENTINO FC','MATHE SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-4-14','sub12','GRUPO A',4,'BENJAMIN FC','MATHE SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-3-bye-15','sub12','GRUPO A',3,'SPORTING JF ONCE',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-4-bye-16','sub12','GRUPO A',4,'TOLENTINO FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-5-17','sub12','GRUPO A',5,'GUERREROS DE MANCHAY','SPORTING JF ONCE','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-6-18','sub12','GRUPO A',6,'GUERREROS DE MANCHAY','MATHE SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-5-19','sub12','GRUPO A',5,'FOVA','MATHE SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-6-20','sub12','GRUPO A',6,'SPORTING JF ONCE','TOLENTINO FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-5-21','sub12','GRUPO A',5,'JYB','TOLENTINO FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-6-22','sub12','GRUPO A',6,'JYB','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-5-bye-23','sub12','GRUPO A',5,'BENJAMIN FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-6-bye-24','sub12','GRUPO A',6,'FOVA',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-7-25','sub12','GRUPO A',7,'GUERREROS DE MANCHAY','TOLENTINO FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-7-26','sub12','GRUPO A',7,'SPORTING JF ONCE','BENJAMIN FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-7-27','sub12','GRUPO A',7,'FOVA','JYB','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-a-7-bye-28','sub12','GRUPO A',7,'MATHE SPORT',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-1-29','sub12','GRUPO B',1,'JM SPORT','FOVITA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-2-30','sub12','GRUPO B',2,'RENACE JUVENTUD','FOVITA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-1-31','sub12','GRUPO B',1,'TALENTOS UNIDOS','CACHORROS FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-2-32','sub12','GRUPO B',2,'JM SPORT','CLUB DEPORTIVO LARA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-1-33','sub12','GRUPO B',1,'DREAM TEAM','CLUB DEPORTIVO LARA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-2-34','sub12','GRUPO B',2,'TALENTOS UNIDOS','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-1-bye-35','sub12','GRUPO B',1,'RENACE JUVENTUD',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-2-bye-36','sub12','GRUPO B',2,'CACHORROS FC',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-3-37','sub12','GRUPO B',3,'RENACE JUVENTUD','CACHORROS FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-4-38','sub12','GRUPO B',4,'RENACE JUVENTUD','CLUB DEPORTIVO LARA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-3-39','sub12','GRUPO B',3,'FOVITA','CLUB DEPORTIVO LARA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-4-40','sub12','GRUPO B',4,'CACHORROS FC','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-3-41','sub12','GRUPO B',3,'JM SPORT','TALENTOS UNIDOS','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-4-42','sub12','GRUPO B',4,'FOVITA','TALENTOS UNIDOS','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-3-bye-43','sub12','GRUPO B',3,'DREAM TEAM',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-4-bye-44','sub12','GRUPO B',4,'JM SPORT',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-5-45','sub12','GRUPO B',5,'RENACE JUVENTUD','DREAM TEAM','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-6-46','sub12','GRUPO B',6,'RENACE JUVENTUD','TALENTOS UNIDOS','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-5-47','sub12','GRUPO B',5,'CLUB DEPORTIVO LARA','TALENTOS UNIDOS','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-6-48','sub12','GRUPO B',6,'DREAM TEAM','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-5-49','sub12','GRUPO B',5,'CACHORROS FC','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-6-50','sub12','GRUPO B',6,'CACHORROS FC','FOVITA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-5-bye-51','sub12','GRUPO B',5,'FOVITA',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-6-bye-52','sub12','GRUPO B',6,'CLUB DEPORTIVO LARA',NULL,'descansa') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-7-53','sub12','GRUPO B',7,'RENACE JUVENTUD','JM SPORT','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-7-54','sub12','GRUPO B',7,'DREAM TEAM','FOVITA','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-7-55','sub12','GRUPO B',7,'CLUB DEPORTIVO LARA','CACHORROS FC','programado') on conflict (id) do nothing;
insert into matches (id,category_id,group_name,round_number,home_team,away_team,status) values ('sub12-grupo-b-7-bye-56','sub12','GRUPO B',7,'TALENTOS UNIDOS',NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-1','17 DE MAYO FECHA 1',1,'CAMPO 1','09:00','JM SPORT','RENACE JUVENTUD','SUB 6','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-2','17 DE MAYO FECHA 1',1,'CAMPO 1','09:40','BENJAMIN FC','CLUB DEPORTIVO LARA','SUB 6','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-3','17 DE MAYO FECHA 1',1,'CAMPO 1','10:20','TOLENTINO FC','GUERREROS DE MANCHAY','SUB 6','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-4','17 DE MAYO FECHA 1',1,'CAMPO 1','11:00','JYB','DREAM TEAM','SUB 8 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-5','17 DE MAYO FECHA 1',1,'CAMPO 2','09:00','BENJAMIN FC','MATHE SPORT','SUB 8 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-6','17 DE MAYO FECHA 1',1,'CAMPO 2','09:40','TOLENTINO FC','JM SPORT','SUB 8 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-7','17 DE MAYO FECHA 1',1,'CAMPO 2','10:20','FOVA','RENACE JUVENTUD','SUB 8 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-8','17 DE MAYO FECHA 1',1,'CAMPO 2','11:00','VASQUEZ FC','GUERREROS DE MANCHAY','SUB 8 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-9','17 DE MAYO FECHA 1',1,'CAMPO 2','12:00','VASQUEZ FC','TALENTOS UNIDOS','SUB 10 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-10','17 DE MAYO FECHA 1',1,'CAMPO 2','12:50','GUERREROS DE MANCHAY','DREAM TEAM','SUB 10 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-11','17 DE MAYO FECHA 1',1,'CAMPO 2','13:40','JM SPORT','TOLENTINO FC','SUB 10 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-12','17 DE MAYO FECHA 1',1,'CAMPO 2','14:30','MATHE SPORT','BENJAMIN FC','SUB 10 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-13','17 DE MAYO FECHA 1',1,'CAMPO 3','09:00','DREAM TEAM','CLUB DEPORTIVO LARA','SUB 12 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-14','17 DE MAYO FECHA 1',1,'CAMPO 3','09:50','MATHE SPORT','JYB','SUB 12 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-15','17 DE MAYO FECHA 1',1,'CAMPO 3','10:40','SPORTING JF ONCE','FOVA','SUB 12 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-16','17 DE MAYO FECHA 1',1,'CAMPO 3','11:30','JM SPORT','FOVITA','SUB 12 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-17','17 DE MAYO FECHA 1',1,'CAMPO 3','12:20','TALENTOS DEL SUR','SPORTING JF ONCE','SUB 10 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-18','17 DE MAYO FECHA 1',1,'CAMPO 3','13:10','TOLENTINO FC','BENJAMIN FC','SUB 12 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-19','17 DE MAYO FECHA 1',1,'CAMPO 3','14:00','TALENTOS UNIDOS','CACHORROS FC','SUB 12 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-20','17 DE MAYO FECHA 1',1,'CAMPO 3','14:50','FOVA','RENACE JUVENTUD','SUB 10 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-21','17 DE MAYO FECHA 1',1,NULL,NULL,'DESCANSA REMANENTE FC SUB 8 (B)',NULL,NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-22','17 DE MAYO FECHA 1',1,NULL,NULL,'DESCANSA REMANENTE FC SUB 10 (A)',NULL,NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-23','17 DE MAYO FECHA 1',1,NULL,NULL,'DESCANSA GUERREROS DE MANCHAY SUB 12 (A)',NULL,NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-24','17 DE MAYO FECHA 1',1,NULL,NULL,'DESCANSA RENACE JUVENTUD SUB 12 (B)',NULL,NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-25','24 DE MAYO FECHA 2',2,'CAMPO 1','09:00','RENACE JUVENTUD','GUERREROS DE MANCHAY','SUB 6','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-26','24 DE MAYO FECHA 2',2,'CAMPO 1','09:40','TOLENTINO FC','BENJAMIN FC','SUB 6','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-27','24 DE MAYO FECHA 2',2,'CAMPO 1','10:20','JM SPORT','CLUB DEPORTIVO LARA','SUB 6','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-28','24 DE MAYO FECHA 2',2,'CAMPO 1','11:00','JM SPORT','DREAM TEAM','SUB 8 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-29','24 DE MAYO FECHA 2',2,'CAMPO 2','09:00','TOLENTINO FC','RENACE JUVENTUD','SUB 8 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-30','24 DE MAYO FECHA 2',2,'CAMPO 2','09:40','MATHE SPORT','REMANENTE FC','SUB 8 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-31','24 DE MAYO FECHA 2',2,'CAMPO 2','10:20','BENJAMIN FC','GUERREROS DE MANCHAY','SUB 8 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-32','24 DE MAYO FECHA 2',2,'CAMPO 2','11:00','FOVA','JYB','SUB 8 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-33','24 DE MAYO FECHA 2',2,'CAMPO 2','12:00','GUERREROS DE MANCHAY','TALENTOS UNIDOS','SUB 10 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-34','24 DE MAYO FECHA 2',2,'CAMPO 2','12:50','VASQUEZ FC','JM SPORT','SUB 10 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-35','24 DE MAYO FECHA 2',2,'CAMPO 2','13:40','BENJAMIN FC','REMANENTE FC','SUB 10 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-36','24 DE MAYO FECHA 2',2,'CAMPO 2','14:30','FOVA','TALENTOS DEL SUR','SUB 10 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-37','24 DE MAYO FECHA 2',2,'CAMPO 3','09:00','TOLENTINO FC','FOVA','SUB 12 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-38','24 DE MAYO FECHA 2',2,'CAMPO 3','09:50','DREAM TEAM','TOLENTINO FC','SUB 10 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-39','24 DE MAYO FECHA 2',2,'CAMPO 3','10:40','MATHE SPORT','RENACE JUVENTUD','SUB 10 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-40','24 DE MAYO FECHA 2',2,'CAMPO 3','11:30','JM SPORT','CLUB DEPORTIVO LARA','SUB 12 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-41','24 DE MAYO FECHA 2',2,'CAMPO 3','12:20','RENACE JUVENTUD','FOVITA','SUB 12 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-42','24 DE MAYO FECHA 2',2,'CAMPO 3','13:10','GUERREROS DE MANCHAY','BENJAMIN FC','SUB 12 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-43','24 DE MAYO FECHA 2',2,'CAMPO 3','14:00','MATHE SPORT','SPORTING JF ONCE','SUB 12 (A)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-44','24 DE MAYO FECHA 2',2,'CAMPO 3','14:50','TALENTOS UNIDOS','DREAM TEAM','SUB 12 (B)','programado') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-45','24 DE MAYO FECHA 2',2,NULL,NULL,'DESCANSA VASQUEZ FC SUB 8 (B)',NULL,NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-46','24 DE MAYO FECHA 2',2,NULL,NULL,'DESCANSA SPORTING JF ONCE SUB 10 (A)',NULL,NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-47','24 DE MAYO FECHA 2',2,NULL,NULL,'DESCANSA JYB SUB 12 (A)',NULL,NULL,'descansa') on conflict (id) do nothing;
insert into calendar_events (id,date_label,round_number,field,time_label,home_team,away_team,category_label,status) values ('cal-48','24 DE MAYO FECHA 2',2,NULL,NULL,'DESCANSA CACHORROS FC SUB 12 (B)',NULL,NULL,'descansa') on conflict (id) do nothing;

-- AVANCE: resultados de Fecha 1 y padrón GUERREROS DE MANCHAY SUB 6.
-- Estos inserts son referenciales para la futura conexión a Supabase/PostgreSQL.
-- En esta versión, la app usa data/results.ts y data/delegateMock.ts como datos mock.

-- Jugadores reales cargados en data/delegateMock.ts:
-- Alexander Chanca Hernandez | DNI 94768639 | 2020-03-11
-- Victor Francesco De la Cruz Mego | DNI 91972988 | 2020-08-15
-- Liam Salcedo Mayta | DNI 92523349 | 2021-09-04
-- Liam Darhiel Chacón Vallejos | DNI 92622043 | 2021-11-11
-- Gianluca Aurelio Pariona Llanterguay | DNI 92695777 | 2021-01-04
-- Hans Steven Quispe Goitia | DNI 91674980 | 2020-01-10
-- Iker Joel Molleapaza Gutierrez | DNI 91903581 | 2020-06-23
-- Dylan Caleb Yajahuanca Arones | DNI 91814200 | 2020-04-14
-- Lucas Anuel Guevara Braco | DNI 92094647 | 2020-11-04
